[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: core health checks
    regression: full suite execution
    krishna: custom marker for Krishna's feature development and testing


    sriram: Sriram test suite

    login: Valid login test
    invalid: Invalid login test cases

    change: Positive change password test
    negative: Negative change password test

    customer: Add customer test
    duplicate: Add existing customer validation test
    attendance: Attendance records test
